image: Visual Studio 2015

before_build:
- nuget restore

build:
  project: PlenteumWallet.sln
  verbosity: minimal

after_build:
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir plenteum-gui-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe plenteum-gui-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE plenteum-gui-%APPVEYOR_REPO_TAG_NAME%
  - 7z a plenteum-gui-%APPVEYOR_REPO_TAG_NAME%-windows.zip plenteum-gui-%APPVEYOR_REPO_TAG_NAME%
  - copy plenteum-gui-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\
  
artifacts:
  - path: plenteum-gui-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: PlenteumGuiRelease
    
deploy:
  - provider: GitHub
    auth_token:
      secure: ZX7Fi2/O/49+ch63DJPBUf2SlUuK2usUYzVEr7z7kVygwD4gt3lFlDIxeQknxJ2g
    artifact: PlenteumGuiRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: plenteum/plenteum-wallet-winforms
      appveyor_repo_tag: true