image: Visual Studio 2015

before_build:
- nuget restore

build:
  project: PlenteumWallet.sln
  verbosity: minimal

artifacts:
  - path: plenteum-guiwallet-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: PlenteumGuiRelease
    
deploy:
  - provider: GitHub
    auth_token:
      secure: ZX7Fi2/O/49+ch63DJPBUf2SlUuK2usUYzVEr7z7kVygwD4gt3lFlDIxeQknxJ2g
    artifact: PlenteumGuiRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: plenteum/plenteum
      appveyor_repo_tag: true